[tool.poetry]
name = "git-hooks-1c"
version = "9.7.0"
description = "Git hooks utilities for 1C:Enterprise"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cujoko/git-hooks-1c"
keywords = ["1c", "git", "pre-commit", "v8reader", "v8unpack", "gcomp"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
gh1c = "git_hooks_1c.__main__:run"

[tool.poetry.dependencies]
python = "^3.7"
cjk-commons = "^3.5"
fleep = "^1.0"
loguru = "^0.4"
parse-1c-build = "^5.13"
plumbum = "^1.6.8"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
