[tool.poetry]
name = "git-hooks-1c"
version = "9.2.1"
description = "Git hooks utilities for 1C:Enterprise"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cujoko/git-hooks-1c"
keywords = ["1c", "git", "pre-commit", "v8reader", "v8unpack", "gcomp"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
gh1c = "git_hooks_1c.__main__:run"

[tool.poetry.dependencies]
python = "^3.7"
cjk-commons = "^3.3"
parse-1c-build = "^5.5"
fleep = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
